run:
  only:
    - tags
  script:
    - 'Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1'
    - 'python3.12 -m pip install --upgrade pip'
    - 'python3.12 -m pip install --upgrade --user pipx'
    - 'refreshenv'
    - 'pipx install build'
    - 'pipx upgrade build'
    - 'pipx install twine'
    - 'pipx upgrade twine'
    - 'refreshenv'
    - 'pyproject-build'
    - 'twine upload --repository gitlab .\dist\*'
