stages:
  - lint
  - deploy

lint_job:
  stage: lint
  script:
    - 'python -m venv .\venv'
    - '.\venv\Scripts\Activate.ps1'
    - 'python -m pip install --upgrade pip'
    - 'pip install ruff'
    - 'ruff check'
    - 'deactivate'

deploy_job:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - 'python -m venv .\venv'
    - '.\venv\Scripts\Activate.ps1'
    - 'python -m pip install --upgrade pip'
    - 'pip install build twine'
    - 'python -m build'
    - '$env:TWINE_PASSWORD = ${CI_JOB_TOKEN}'
    - '$env:TWINE_USERNAME = "gitlab-ci-token"'
    - 'twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi .\dist\*'
    - 'release-cli create --description "./docs/release-latest.md" --tag-name "${CI_COMMIT_TAG}"'
    - 'deactivate'
