run:
  only:
    - tags
  script:
    - 'Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1'
    - 'python3.12 -m pip install --upgrade pip'
    - 'python3.12 -m pip install --upgrade --user pipx'
    - 'python3.12 -m pipx ensurepath'
    - 'refreshenv'
    - 'pipx install build'
    - 'pipx upgrade build'
    - 'pipx install twine'
    - 'pipx upgrade twine'
    - 'refreshenv'
    - 'pyproject-build'
    - '$env:TWINE_PASSWORD = ${CI_JOB_TOKEN}'
    - '$env:TWINE_USERNAME = "gitlab-ci-token"'
    - 'twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi .\dist\*'
